# Use an official Elixir runtime as a parent image.
FROM elixir:latest

# Create app directory and copy the Elixir projects into it.
RUN mkdir /app
COPY . /app
WORKDIR /app

# Install Hex package manager.
RUN mix local.hex --force

# Compile the project.
RUN mix deps.get
RUN mix do compile

CMD mix cluster.clean