# NOTE: The service account `default:default` already exists in k8s cluster.
# You can create a new account following like this:
#---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployment-creater
rules:
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["pods", "deployments"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-creater
  namespace: default
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: service-account
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: deployment-creater # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
