apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: service-account
      containers:
      - name: server
        image: aperence/bomberman
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          # Variables to connect to our Postgres server.
          - name: KUBERNETES
            value: "true"
          - name: ERLANG_COOKIE
            value: "secret"
          - name: username
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: password
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: password
          - name: db
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: db
          - name: WAIT_HOSTS
            value: "mongodb:27017"
          - name: MONGODB_URI
            value: "mongodb://$(username):$(password)@$(WAIT_HOSTS)/$(db)"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 4000
